### ISSUE TITLE
How to integrate into existing project?

### ISSUE THREAD

**Issue by Steven4294** [steven-tey/novel#10]
Is there any instructions on how to integrate this into an existing project? Specifically I am looking to add this to an angular project.

**Comment by dherault** [comment]
Same here for a react project, would love to see a documentation arise. Much love.

**Comment by steven-tey** [comment]
Contributions welcome here for the setup docs!

Ideally we'd want to have a similar setup experience as https://ui.shadcn.com/ (shoutout to my man @shadcn) where you copy and paste the code into your own codebase.

In fact, folks are already doing this successfully:
- https://twitter.com/driaug_/status/1670519652034723841
- https://twitter.com/graeme_fulton/status/1670782603073404929

**Comment by TerminalFi** [comment]
I can't access those tweets. Can anyone provide a example for nextjs ? I am migrating (or trying) from the Affine Editor to Novel

**Comment by z4nr34l** [comment]
@TerminalFi here you go: https://github.com/vercel/platforms

**Comment by TerminalFi** [comment]
> @TerminalFi here you go: https://github.com/vercel/platforms

Yea…I don’t think that’s using novel. But thanks ! I actually decided to just push forward with Lexical which already has everything needed including block support.

**Comment by z4nr34l** [comment]
@TerminalFi this template is build with novel. Please read readme:

```markdown
Built on open source

This working demo site was built using the Platforms Starter Kit and:

[Next.js](https://nextjs.org/) as the React framework
[Tailwind](https://tailwindcss.com/) for CSS styling
[Prisma](https://prisma.io/) as the ORM for database access
[Novel](https://novel.sh/) for the WYSIWYG editor
[Vercel Postgres](https://vercel.com/storage/postgres) for the database
[Vercel Blob](https://vercel.com/storage/blob) for image uploads
[NextAuth.js](https://next-auth.js.org/) for authentication
[Tremor](https://tremor.so/) for charts
[Vercel](http://vercel.com/) for deployment
```

You just need dig down in catalogs to see how it's implemented.

Happy coding! :D

**Comment by TerminalFi** [comment]
Again, not really built on novel. Novel isn’t a dependency nor is it imported anywhere. It looks like it’s copy and pasted code from novel into this app. Which doesn’t make using novel as a package intuitive. 

Either way I’ve moved on and I happy with Lexical.

**Comment by steven-tey** [comment]
@TerminalFi that's correct, we don't have a package yet – it's being worked on in #87 

Lexical is a solid choice – best of luck!
