### ISSUE TITLE
Custom Endpoint/ChimeraGPT

### ISSUE THREAD

**Issue by Sergo1217** [steven-tey/novel#103]
When deploying Vercel Server, I want to be able to specify an endpoint. This is necessary for services like ChimeraGPT to work.

**Comment by nerdneilsfield** [comment]
me too.

**Comment by steven-tey** [comment]
Yes – since we're using the `ai` SDK, you should be able to swap OpenAI out for other supported LLMs fairly easily! 

Here are the docs: https://sdk.vercel.ai/docs
