### ISSUE TITLE
Table support

### ISSUE THREAD

**Issue by Eun** [steven-tey/novel#107]
Hey, first of thanks for developing and open sourcing novel 👍 

It would be great if somebody could add proper table support.

Personally I like the approach of vrite: https://editor.vrite.io/

It also uses tiptap, so maybe you can borrow the code?
Code for the standalone editor is here: https://github.com/vriteio/vrite/tree/main/apps/web/src/views/standalone-editor

**Comment by steven-tey** [comment]
@ashrafchowdury has started on this on #47! There are a few bugs that need to be resolved before it can be merged but it's a pretty good start!

**Comment by ghoshsanjoy78** [comment]
Any update on adding table support ?

**Comment by davidliudev** [comment]
Same question here. Any udpates on adding table support?

**Comment by andrewdoro** [comment]
I'll close this as there is already a discussion about this
https://github.com/steven-tey/novel/discussions/40
