### ISSUE TITLE
Blob early access 

### ISSUE THREAD

**Issue by volnei** [steven-tey/novel#108]
How can I get early access to Vercel blob 🙏?

**Comment by MasonWang025** [comment]
Sign up on the waitlist: https://vercel.com/storage/blob

**Comment by volnei** [comment]
I’m already on the waitlist. But accordingly with project description. 

![IMG_3284](https://github.com/steven-tey/novel/assets/619072/197038ea-2b89-4780-af4d-ee8d2b5899bd)

I’ve tried from twitter with no response.

**Comment by volnei** [comment]
Done! Thank you so much!!!

**Comment by steven-tey** [comment]
@volnei you should've been added now! :)
