### ISSUE TITLE
failed to fetch the chat response

### ISSUE THREAD

**Issue by Ssssuky** [steven-tey/novel#109]
HELP!!!
I have deployed it on the vercel and I try to type with autocomplete but failed
it report "failed to fetch the chat response"
[
![image](https://github.com/steven-tey/novel/assets/140771280/0bd403a0-9718-4e8a-8fcc-541fe29a02b9)
](url)

**Comment by marscome** [comment]
Check your api key.

**Comment by steven-tey** [comment]
This is probably due to an invalid/rate limited API key – closing for now!
