### ISSUE TITLE
Custom LLMs & APIs Endpoints

### ISSUE THREAD

**Issue by LSXAxeller** [steven-tey/novel#116]
Will it support the local llm models like LlaMa and RWKV using the local APIs like oobobga Text Generation WebUI ? 
This would solve the problems of insufficient OpenAI credits and limited tokens and the countries that ChatGPT access is still unavailable in yet

**Comment by steven-tey** [comment]
Yes – since we're using the `ai` SDK, you should be able to swap OpenAI out for other supported LLMs fairly easily! 

Here are the docs: https://sdk.vercel.ai/docs
