### ISSUE TITLE
Multiple Editors in one page which have different local storage keys

### ISSUE THREAD

**Issue by dirums** [steven-tey/novel#123]
Hi team,
First of all thank you for this awesome project.
I wanted to know how I can add multiple editors in one page which have thier own local storage key, value. Right now it save only one local storage key: ```novel__content``` where all the content is being saved.

If there are two separate editors then it overrides each other's values.

Please help me with this.

**Comment by steven-tey** [comment]
Your wish is my command!

Version 1.0.8 now has a `storageKey` that supports that: https://github.com/steven-tey/novel/releases/tag/Latest
