### ISSUE TITLE
Style injection caused tailwind override css priorities

### ISSUE THREAD

**Issue by btxakita** [steven-tey/novel#128]
Novel will inject CSS directly into Root, included tailwindcss. Which could potentially override stylesheets priorities when you have tailwind in the project yourself.

**Comment by mawnir** [comment]
I have this issue.. I'm using Chakra ui. 
Why linking the library to Tailwind?

**Comment by JimmyLv** [comment]
I also have this issue, broken the whole page styling.

**Comment by luke-ae** [comment]
+1

**Comment by evertjr** [comment]
Same problem, loading this component breaks several styles across the application. I'm using tailwind

**Comment by eyalcohen4** [comment]
I can see the issue.. 
@steven-tey I'm thinking of adding a `novel-` prefix to the package tailwind classes we import, wdyt? 
is there a better option?

**Comment by sarimrmalik** [comment]
+1 to this

**Comment by tomyda** [comment]
+1 to this

**Comment by jaqnjilai** [comment]
fyi, i downgraded to 0.1.17 for now to fix this issue

**Comment by eyalcohen4** [comment]
Hey everyone! I started a PR but would love help there. There's one issue I face (described in the PR) which looking for a solution. I'll have more time to research it in the rest of the week.

**Comment by DataRM-JB** [comment]
Can we get an update on this? Having the same tailwind issue, cant use the forked repo, can we get this committed please? :)

**Comment by steven-tey** [comment]
Sorry for the delay here! This should be fixed in `novel@0.1.22`: https://github.com/steven-tey/novel/releases/tag/0.1.22
