### ISSUE TITLE
defaultValue is not settable 

### ISSUE THREAD

**Issue by mirik999** [steven-tey/novel#132]
hi there , how to set default content ( plain html code from previouse rich text editor, e,g, result came from DB )

e.g.

```
<Editor
                className={css.editorContainer}
                defaultValue={'<div>test</div>'}
                content={'<div>test</div>'}
                onDebouncedUpdate={onDebounceUpdate}
            />
```

the result is just editor with placeholder ...

**Comment by tdwhite0** [comment]
I was confused by this as well and what probably happened was you used the component the first time and it stored the defaultContent in local storage. Then when you tried to update it it was still pulling from there. Try clearing local storage.

**Comment by luke-ae** [comment]
You need to add a `storageKey` to change it

**Comment by jlia0** [comment]
> ```
>     if (editor && content && !hydrated) {
>       editor.commands.setContent(content)
>       setHydrated(true)
>     }
>   }, [editor, content, hydrated]) ```       this is where you hydrate the content. Content must be in json format of tiptap nodes. You cannot inject plain html code to Editor.You can parse string as text, bullet point, headlines type of tiptap nodes. 
> ```

Where can I get the `editor` instance?

**Comment by jt6677** [comment]
> > ```
> >     if (editor && content && !hydrated) {
> >       editor.commands.setContent(content)
> >       setHydrated(true)
> >     }
> >   }, [editor, content, hydrated]) ```       this is where you hydrate the content. Content must be in json format of tiptap nodes. You cannot inject plain html code to Editor.You can parse string as text, bullet point, headlines type of tiptap nodes. 
> > ```
> 
> Where can I get the `editor` instance?

```js

import { Content, EditorContent, useEditor } from '@tiptap/react'

  const editor = useEditor({
    extensions: TiptapExtensions,
    editorProps: TiptapEditorProps,
    onUpdate: (e) => {
      setSaveStatus('Unsaved')
      const selection = e.editor.state.selection
      const lastTwo = e.editor.state.doc.textBetween(selection.from - 2, selection.from, '\n')

      if (lastTwo === '++' && !isLoading) {
        e.editor.commands.deleteRange({
          from: selection.from - 2,
          to: selection.from,
        })
        // complete(e.editor.storage.markdown.getMarkdown())
        complete(e.editor.getText())
      } else {
        debouncedUpdates(e)
      }
    },
    autofocus: 'end',
  })
```
in the same function Editor

**Comment by jlia0** [comment]
> > > ```
> > >     if (editor && content && !hydrated) {
> > >       editor.commands.setContent(content)
> > >       setHydrated(true)
> > >     }
> > >   }, [editor, content, hydrated]) ```       this is where you hydrate the content. Content must be in json format of tiptap nodes. You cannot inject plain html code to Editor.You can parse string as text, bullet point, headlines type of tiptap nodes. 
> > > ```
> > 
> > 
> > Where can I get the `editor` instance?
> 
> ```js
> import { Content, EditorContent, useEditor } from '@tiptap/react'
> 
>   const editor = useEditor({
>     extensions: TiptapExtensions,
>     editorProps: TiptapEditorProps,
>     onUpdate: (e) => {
>       setSaveStatus('Unsaved')
>       const selection = e.editor.state.selection
>       const lastTwo = e.editor.state.doc.textBetween(selection.from - 2, selection.from, '\n')
> 
>       if (lastTwo === '++' && !isLoading) {
>         e.editor.commands.deleteRange({
>           from: selection.from - 2,
>           to: selection.from,
>         })
>         // complete(e.editor.storage.markdown.getMarkdown())
>         complete(e.editor.getText())
>       } else {
>         debouncedUpdates(e)
>       }
>     },
>     autofocus: 'end',
>   })
> ```
> 
> in the same function Editor

Ah I see thanks, I thought I can get the `editor` instance without customizing the package...

**Comment by jt6677** [comment]
> > > > ```
> > > >     if (editor && content && !hydrated) {
> > > >       editor.commands.setContent(content)
> > > >       setHydrated(true)
> > > >     }
> > > >   }, [editor, content, hydrated]) ```       this is where you hydrate the content. Content must be in json format of tiptap nodes. You cannot inject plain html code to Editor.You can parse string as text, bullet point, headlines type of tiptap nodes. 
> > > > ```
> > > 
> > > 
> > > Where can I get the `editor` instance?
> > 
> > 
> > ```js
> > import { Content, EditorContent, useEditor } from '@tiptap/react'
> > 
> >   const editor = useEditor({
> >     extensions: TiptapExtensions,
> >     editorProps: TiptapEditorProps,
> >     onUpdate: (e) => {
> >       setSaveStatus('Unsaved')
> >       const selection = e.editor.state.selection
> >       const lastTwo = e.editor.state.doc.textBetween(selection.from - 2, selection.from, '\n')
> > 
> >       if (lastTwo === '++' && !isLoading) {
> >         e.editor.commands.deleteRange({
> >           from: selection.from - 2,
> >           to: selection.from,
> >         })
> >         // complete(e.editor.storage.markdown.getMarkdown())
> >         complete(e.editor.getText())
> >       } else {
> >         debouncedUpdates(e)
> >       }
> >     },
> >     autofocus: 'end',
> >   })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the same function Editor
> 
> Ah I see thanks, I thought I can get the `editor` instance without forking and customizing the package...

If you want to do any customization, you need to pull entire package out of node_module into your src.

**Comment by steven-tey** [comment]
Apologies for the delay here! 

`novel@0.1.21` now has a new `disableLocalStorage` prop that lets you disable reading / writing content from local storage!

Check out the release: https://github.com/steven-tey/novel/releases/tag/0.1.21
