### ISSUE TITLE
change default place holder

### ISSUE THREAD

**Issue by okandavut** [steven-tey/novel#134]
Hi,

Thanks for this editor and it's really useful. I just wanted to ask how to change defaultPlaceholder or disable AI side of editor?

Thanks again @steven-tey

**Comment by sarimrmalik** [comment]
Set the `defaultValue` to an empty string, for e.g: `<Editor defaultValue="" />`.

**Comment by okandavut** [comment]
> default

<img width="487" alt="image" src="https://github.com/steven-tey/novel/assets/10600157/76898f9f-cdc8-42fc-ad29-a6d490eed66f">


You can see on image it's displaying already the text

I updated like you said.

<img width="534" alt="image" src="https://github.com/steven-tey/novel/assets/10600157/0f288725-e7c8-477a-980e-b31dde41a9f5">
 @sarimrmalik

**Comment by sarimrmalik** [comment]
Yeap, this is good. This is the `placeholder` text to get the user started, if you click into the editor, the text should disappear as expected. 

I don't think there is a way to edit the `placeholder` for now (might be wrong).

**Comment by tiavina-mika** [comment]
You can do it by overidding the Placeholder extensions via the `extensions ` props

**Comment by wwwDESIGN-basti** [comment]
@tiavina-mika 
can you please show us an example for the Placeholder extension?

**Comment by andrewdoro** [comment]
https://novel.sh/docs/guides/tailwind/extensions#default-extensions you can to that now
```tsx

const PlaceholderExtension = Placeholder.configure({
  placeholder: ({ node }) => {
    if (node.type.name === "heading") {
      return `Heading ${node.attrs.level}`;
    }
    return "Press '/' for commands, or '++' for AI autocomplete...";
  },
  includeChildren: true,
});

```
