### ISSUE TITLE
defaltValue is ignored

### ISSUE THREAD

**Issue by krehak** [steven-tey/novel#137]
This is my component using novel editor:
```tsx
import React, { useId } from 'react';
import { Editor } from 'novel';

type TextEditorProps = {
    value: string,
    onChange: (value: string) => void,
};

export default function TextEditor(props: TextEditorProps) {
    const id = useId();

    return <>
        <Editor
            defaultValue={props.value}
            onUpdate={(editor) => props.onChange(editor?.getHTML() || '')}
            storageKey={`novel-content--${id}`}
        />
    </>;
}
```

I have a component to create a new article in a modal. When the user opens a modal, he can use the editor to type the text. When he closes the modal, I reset the value to empty and when I reopen the modal, the editor is empty. But when I type some text, reload the website, and open the modal again, the old value is present.

Is there an option to ignore saving contents to localstorage? I want to have a new value on each instance, and I don't see any benefit in saving the content to localstorage in my application.

**Comment by awilliamson10** [comment]
I'm also running into this.

**Comment by benhassineb** [comment]
I'm using this workaround until this issue gets resolved

```
export default function CustomEditor(props: TextEditorProps) {
    //TODO
    const randomId = uuidv4();


    return (
        <Editor  storageKey={randomId} />
    )
}
```

**Comment by jonschlinkert** [comment]
> I'm using this workaround until this issue gets resolved

I haven't looked at the code in this library yet, but I'm assuming that localstorage is the default, and this could create an entry for every ID. If that is the case, you might consider adding some kind of garbage collection as well.

**Comment by awilliamson10** [comment]
> > I'm using this workaround until this issue gets resolved
> 
> I haven't looked at the code in this library yet, but I'm assuming that localstorage is the default, and this could create an entry for every ID. If that is the case, you might consider adding some kind of garbage collection as well.

Good point, I'm using this currently.

```
<Editor editorProps={editorProps}
    className="border-none"
    defaultValue={JSON.parse(writing.content)}
    onUpdate={() => {
        setSaved(false)
    }}
    onDebouncedUpdate={(editor: any) => {
        save(editor.getJSON().content)
        localStorage.clear()
    }}
    storageKey={`writing-${randomId}`}
/>
```

**Comment by steven-tey** [comment]
Apologies for the delay here! 

`novel@0.1.21` now has a new `disableLocalStorage` prop that lets you disable reading / writing content from local storage!

Check out the release: https://github.com/steven-tey/novel/releases/tag/0.1.21
