### ISSUE TITLE
Request - expose underlying tiptap editor component

### ISSUE THREAD

**Issue by jeremypve** [steven-tey/novel#144]
As far as I can tell, there is no way to directly access the underlying tiptap editor, which limits customizability. e.g I want to make imperative calls to the editor commands from elsewhere in my app. 

Also - there is no way to disable the default tiptap extensions provided. I can pass additional ones, but even using the same type they do not override the previous ones in the array. 

Thanks for creating this awesome tool - excited to see it develop!

**Comment by andrewdoro** [comment]
this PR #136 exposes a `useEditor` hook, related to extensions configuration I also added a util function for changing the styling, but I think we can have a config object to enable-disable them individually

**Comment by jeremypve** [comment]
That's excellent! Hope it can be merged soon.

**Comment by andrewdoro** [comment]
https://novel.sh/docs/components/utils/use-editor

**Comment by akdeb** [comment]
@andrewdoro `const { editor } = useEditor()` only returns an editor when the child component is a child of `EditorContent` but not `EditorRoot`. Are you seeing this as well?

**Comment by andrewdoro** [comment]
Yep you are right I have to update the docs

**Comment by akdeb** [comment]
Thanks for confirming. I am currently working around this with `slotBefore`. Do you know of any other alternatives?

**Comment by akdeb** [comment]
Here's an updated README PR: https://github.com/akdeb/novel/pull/1
