### ISSUE TITLE
The draggable icon is misplaced in ordered and unordered lists.

### ISSUE THREAD

**Issue by Adonis0123** [steven-tey/novel#146]
![bug](https://github.com/steven-tey/novel/assets/46788304/b443b539-4665-4977-9833-4a313a624234)

**Comment by Adonis0123** [comment]
Thank you, @p1yu5h, I also want to ask a question, how to destroy the drag button when the mouse leaves the editing container

**Comment by p1yu5h** [comment]
Hi @Adonis0123 

I just stumbled upon this awesome repo, so not super familiar with the codebase. But I think you can do something like this (not sure if this is the right approach, but seems to work for me):

Add a new prop `mouseleave` in `drag-and-drop.tsx`

```
 mouseleave: (view, event) => {
    const { dom } = view; // Editor element
    const editorRect = dom.getBoundingClientRect();
    const { clientX: mouseX, clientY: mouseY } = event;
    
    if (
      mouseX < editorRect.left ||
      mouseX > editorRect.right ||
      mouseY < editorRect.top ||
      mouseY > editorRect.bottom
    ) {
      // Call this function if mouseleave event callback is fired outside the Editor element
      hideDragHandle();
    }
 }
```

**Comment by Adonis0123** [comment]
> Hi @Adonis0123
> 
> I just stumbled upon this awesome repo, so not super familiar with the codebase. But I think you can do something like this (not sure if this is the right approach, but seems to work for me):
> 
> Add a new prop `mouseleave` in `drag-and-drop.tsx`
> 
> ```
>  mouseleave: (view, event) => {
>     const { dom } = view; // Editor element
>     const editorRect = dom.getBoundingClientRect();
>     const { clientX: mouseX, clientY: mouseY } = event;
>     
>     if (
>       mouseX < editorRect.left ||
>       mouseX > editorRect.right ||
>       mouseY < editorRect.top ||
>       mouseY > editorRect.bottom
>     ) {
>       // Call this function if mouseleave event callback is fired outside the Editor element
>       hideDragHandle();
>     }
>  }
> ```

thank you very much, it is aslso work for me, have a nice day!
