### ISSUE TITLE
disabling some features on list of editor options

### ISSUE THREAD

**Issue by okandavut** [steven-tey/novel#147]
Hi,

Thanks for package and it's really useful! @steven-tey 

How can i disable the items in the list

I mean i wanted to disable first two + image upload and I don't know how to do it sorry if i am idiot :) 

![image](https://github.com/steven-tey/novel/assets/10600157/e5d440f0-ce0a-4574-9e1c-6ea5a2b5ce13)

**Comment by cristigoia** [comment]
You can find the code here [slash-command.tsx](https://github.com/steven-tey/novel/blob/main/packages/core/src/ui/editor/extensions/slash-command.tsx#L77-L91) (line 77-91) and can delete or comment it.

**Comment by okandavut** [comment]
I can do that but this will change the package right? that means after update my code will be deleted and I need to update again isn't it?

**Comment by cristigoia** [comment]
This way you are changing the package, yes. Not sure if it's accessible otherwise right now, but might be cool to have a commands list and settings in the future.

**Comment by okandavut** [comment]
I checked now also it's not possible to change it on package.

**Comment by MarkLyck** [comment]
I also want to delete these 2 options. @steven-tey 🙏

**Comment by jaqnjilai** [comment]
@MarkLyck @okandavut  see https://www.npmjs.com/package/patch-package to make changes after downloading npm packages

**Comment by sergeysova** [comment]
@okandavut, I've already implemented the changes in my fork of the package, which you can find here: https://github.com/sergeysova/craft. I'm committed to keeping up with updates to the Novel and introducing new features.

Is this what you were looking for?

**Comment by jt6677** [comment]
I am having a hard time understanding this. If you want customization, why cannot pull the code from node_moudels into your src?

**Comment by steven-tey** [comment]
Great feedback @okandavut! 

We just added a Context Provider in #190 – maybe we can use that to configure the slash command menu items as well? PRs welcome :)

**Comment by andrewdoro** [comment]
https://novel.sh/docs/guides/tailwind/slash-command you can now customize every item for menus
