### ISSUE TITLE
Bubble menu still opens when `editable: () => false` is set

### ISSUE THREAD

**Issue by MarkLyck** [steven-tey/novel#153]
novel.sh doesn't have any good way of rendering the output.

tiptap has 3 methods:

JSON, HTML, and rendering tip-tap in read-only mode by setting editable to false.

However when I pass `editable: () => false` in `editorProps` the bubble menu still opens and allows anyone to edit selected the selected content.

I tried converting the JSON to HTML instead, but this has 2 problems.

1. https://tiptap.dev/guide/output#option-2-generate-html-from-prosemirror-json generating html from the JSON requires passing the extensions. This "would" work if you would please add an export of the extensions from novel, so I can import them.

2. The styles won't always match. Since my application has default styles, and novel.sh has it's own styles, my content looks different inside the novel Editor, and when it's rendered in plain HTML. I don't want to give my users a bad experience of the output not looking the same as the input. This is why I'm trying to use the `Editor` to render the output, instead of converting it.

**Comment by 101budspencer** [comment]
How did you disable editable mode?
I tried this:
```
<Editor
				disableLocalStorage
				editorProps={{ editable: () => false }}
			/>
```

But it still lets me type.

**Comment by Gyurmatag** [comment]
Hi! @MarkLyck have you got any luck with setting the editable to false and not showing the bubble menu?

**Comment by lfgtavora** [comment]
same here, the bubble menu should appears in editable mode only. At this point i cant go to production with this issue :/

**Comment by motoya-k** [comment]
Hi.
I had the same situation and raised the PR here.
https://github.com/steven-tey/novel/pull/249

https://tiptap.dev/api/extensions/bubble-menu
The default behavior of the `bubble menu` seems to hide it when 'editable' is falsy.
However, in the current implementation, it appears to be overridden by `shouldShow`.

I have modified it within the PR to also consider `editor.isEditable`.

**Comment by parthmahajan008** [comment]
@motoya-k @MarkLyck  i downloaded novel package using standard npm procdedure, but this editable method still doesnt seem to work for me, any help?

**Comment by andrewdoro** [comment]
https://novel.sh/docs/components/editor-bubble new approach should be fully customizable 
[0.2.0-canary.0](https://www.npmjs.com/package/novel/v/0.2.0-canary.0)
As a solution to this problem
1. Hide the Bubble Menu from React tree
2. Ovewrite `shouldShow` from `tippyOptions`
