### ISSUE TITLE
Copy and paste certain markdown will break the editor

### ISSUE THREAD

**Issue by jt6677** [steven-tey/novel#154]
"- Item 2 "   ,  " 2. Second item" and "- [ ] Unchecked box " , copy content between the quotes and paste it in the editor will cause the editor to freeze. 

"*This is italicized text*"  and "**This is bold text**" are fine. 

"## Heading 2" won't affect any styling.

**Comment by steven-tey** [comment]
Can't reproduce this – can you share a screen recording of how this is happening?

**Comment by jt6677** [comment]
I think those markdown texts no longer produce freezes. 
They just do not change the format
work:
## **This is bold text**
*This is italicized text*

does not work:
- Item 2
1. asdasd
- [ ] asdasd
### Heading

**Comment by arrlancore** [comment]
I think current version is not freezing when paste markdown text. I also work to this PR https://github.com/steven-tey/novel/pull/189 to support basic markdown pasting text.

**Comment by steven-tey** [comment]
Thanks for the PR @arrlancore!

We're actually using the amazing [aguingand/tiptap-markdown](https://github.com/aguingand/tiptap-markdown) package by @aguingand for this so was able to enable this in a one-line PR over at https://github.com/steven-tey/novel/pull/191 😄
