### ISSUE TITLE
SlashCommand Doesn't support dark mode

### ISSUE THREAD

**Issue by MarkLyck** [steven-tey/novel#156]
<img width="492" alt="Screenshot 2023-09-07 at 21 47 21" src="https://github.com/steven-tey/novel/assets/6841110/4c8e6489-4e72-401d-9735-c8b704767929">

**Comment by shaan-alam** [comment]
The codeblocks and todos also do not support dark mode.

![image](https://github.com/steven-tey/novel/assets/48273777/69ee4a79-731d-4373-998e-0a54afd7e83b)

![image](https://github.com/steven-tey/novel/assets/48273777/28f558be-794a-4b5d-b15f-2b6cf7b0b522)

**Comment by arthureberledev** [comment]
Did you find a solution for it? Having the same issue currently

**Comment by andrewdoro** [comment]
https://novel.sh/docs/quickstart#anatomy components are now modular, you can style them for your specific case
