### ISSUE TITLE
How to edit the slash commands

### ISSUE THREAD

**Issue by rightson1** [steven-tey/novel#159]
I want to edit the slash commands, to add my own  , how can i do that. Could  you guys also please develop a nice documentation

**Comment by sergeysova** [comment]
You can join the fork project with the aim of customization and documentation: https://github.com/sergeysova/craft

**Comment by wwz223** [comment]
I have the same question, do you have a good idea ？

**Comment by dsanchez07** [comment]
Any update on this?

**Comment by andrewdoro** [comment]
https://novel.sh/docs/guides/tailwind/slash-command you can now customize each extension, especially the slash command feature
