### ISSUE TITLE
Allow images to be stored elsewhere?

### ISSUE THREAD

**Issue by Elon-Mask12** [steven-tey/novel#162]
Now, image uploading is only allowed to vercel blob storage, exposing a function would be nice.
Thanks!

**Comment by ThiagoMaurat** [comment]
You can create a api call on /api/upload to store the image where you want. I did something like this to store on supabase: 



    const reader = req.body?.getReader();

    const stream = await reader?.read();

    if (!stream?.value) return;

    const filename = `${randomUUID()}`;

    const uint8Array = new Uint8Array(stream.value);

    const blob = new Blob([uint8Array], { type: "image/png" });

    const fileBody = new File([blob], filename, {
      type: "image/png",
    });

    await supabase.storage.from("blog-images").upload(filename, fileBody);

    const { data } = await supabase.storage
      .from("blog-images")
      .getPublicUrl(filename);

    return NextResponse.json(
      {
        url: data.publicUrl,
      },
      { status: 200 }
    );

**Comment by Elon-Mask12** [comment]
Hey, thanks for the reply,
but vercel has a limit on the size of the body you can send to /api right?
I was hoping for doing something client side => getting presigned url, then upload it from client

**Comment by learningqna** [comment]
is there was any way to change the api url by sending as a props? because i need a dynamic route.

**Comment by arthureberledev** [comment]
> Hey, thanks for the reply, but vercel has a limit on the size of the body you can send to /api right? I was hoping for doing something client side => getting presigned url, then upload it from client

I've implemented such a solution with supabase as well:

1. Create an api route for creating the signed upload url (mine is under `/api/uploads`)

```
// fix supabase issue with edge functions
export function createEdgeHandlerClient(req: Request) {
  const cookies = new RequestCookies(req.headers) as any;
  return createRouteHandlerClient<Database>({ cookies: () => cookies });
}
```

```
export const runtime = "edge";

export async function GET(req: Request) {
  try {
    const supabase = createEdgeHandlerClient(req);
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      throw new UnauthorizedError();
    }

    const fileId = uuidv4();

    const { data, error } = await supabase.storage
      .from("uploads")
      .createSignedUploadUrl(`users/${userId}/files/${fileId}`);

    if (error) {
      throw error;
    }
    if (!data) {
      throw new ApplicationError("Failed to create signed upload url");
    }

    return new Response(
      JSON.stringify({
        fileId,
        token: data.token,
        path: data.path,
      }),
      {
        status: 200,
        headers: { "Content-Type": "application/json" },
      },
    );
  } catch (error) {
    // handle error
  }
}
```

2. Create another api route to get the create a signed url for reading the file (mine is under `/api/uploads/[fileId]`

```
export async function GET(
  req: Request,
  {
    params: { fileId },
  }: {
    params: { fileId: string };
  },
) {
  try {
    const supabase = createEdgeHandlerClient(req);
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      throw new UnauthorizedError();
    }

    const { data, error } = await supabase.storage
      .from("uploads")
      .createSignedUrl(`users/${userId}/files/${fileId}`, 60 * 60 * 24 * 7); // 1 week

    if (error) {
      throw error;
    }
    if (!data) {
      throw new ApplicationError("Failed to create signed url.");
    }

    return new Response(JSON.stringify({ signedUrl: data.signedUrl }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    // handle error 
  }
}
```

3. For the frontend part simply first create and return the signed upload url, upload the file and finally return the signed url for reading it:

```
export function handleImageUpload(file: File, documentId: string) {
  const supabase = createClientComponentClient();

  return new Promise((resolve, reject) => {
    toast.promise(
      async () => {
        let id: string;

        // 1. Create a signed upload url and upload the file
        try {
          // I use ky for fetching the signed upload url
          const data = await ky
            .get(`/api/uploads`)
            .json();

          // And valibot for parsing the response
          const { fileId, token, path } = parse(
            CreatedSignedUploadUrlSchema,
            data,
          );

          const { error } = await supabase.storage
            .from("uploads")
            .uploadToSignedUrl(path, token, file);

          if (error) {
            throw error;
          }

          id = fileId;
        } catch (error) {
          // handle error
          return reject(error);
        }

        // 2. Create a signed url to read the file
        try {
          const data = await ky
            .get(`/api/uploads/${id}`)
            .json();
          const { signedUrl } = parse(CreatedSignedUrlDataSchema, data);

          // Preload the image
          const image = new Image();
          image.src = signedUrl;
          image.onload = () => resolve(signedUrl);
        } catch (error) {
          // handle error
          return reject(error);
        }
      },
      {
        loading: "Uploading image...",
        success: "Image uploaded successfully.",
        error: (error) => error.message,
      },
    );
  });
}
```

**Comment by Elon-Mask12** [comment]
woah, this is really cool. thanks a ton <3

**Comment by redenvalerio** [comment]
Here is what I did to save the image to my pocketbase server

`  
const reader = await request.body?.getReader();

  let totalData: Uint8Array | null = null;
  let streamChunk;

  if (!reader) return;

  while (!(streamChunk = await reader.read()).done) {
    const chunk = streamChunk.value;

    if (chunk) {
      if (!totalData) {
        totalData = chunk;
      } else {
        const newData: Uint8Array = new Uint8Array(
          totalData.length + chunk.length
        );
        newData.set(totalData, 0);
        newData.set(chunk, totalData.length);
        totalData = newData;
      }
    }
  }

  if (!totalData) {
    throw new Error("No data received from the stream.");
  }

  const filename = `${randomUUID()}`;

  const uint8Array = new Uint8Array(totalData);

  const blob = new Blob([uint8Array], { type: "image/png" });

  const formData = new FormData();
  formData.append("file", blob);
  formData.append("name", filename);

  console.log(JSON.stringify(request.body));

  const record = await uploadFile("files", formData); 
  `
  
  based on @ThiagoMaurat 's code

**Comment by AakashKB** [comment]
@arthureberledev how did you modify the editor on the frontend to use details from client side upload? There is no prop to change editor mechanics on the client side as far as I can tell

**Comment by arthureberledev** [comment]
> @arthureberledev how did you modify the editor on the frontend to use details from client side upload? There is no prop to change editor mechanics on the client side as far as I can tell

I am using a fork for this till the editor is more extensible. But it essentially replaces some code of the [UploadImagesPlugin](https://github.com/steven-tey/novel/blob/main/packages/core/src/ui/editor/plugins/upload-images.tsx) which in turn is added [here](https://github.com/steven-tey/novel/blob/b4526fc63175caed02bdbfbee490e87b3466dd1c/packages/core/src/ui/editor/extensions/index.tsx#L97) to the extension list. Maybe it works if you add a new extension to the list?
