### ISSUE TITLE
Expose Internal Editor State for External Use

### ISSUE THREAD

**Issue by mkrkelj1** [steven-tey/novel#163]
Is there a way to directly access the internal state of the editor for some custom functionalities, like copying content to the clipboard? 

Currently, I'm relying on the `onUpdate` callback to capture the content, save it to state, then doing whatever with it.

**Comment by andrewdoro** [comment]
should be possible now with either `useEditor` hook or just onCreated callback on `EditorContent`
[0.2.0-canary.0](https://www.npmjs.com/package/novel/v/0.2.0-canary.0)
https://novel.sh/docs/components/utils/use-editor
https://novel.sh/docs/components/editor-content

**Comment by jonkurtis** [comment]
this only seems to work if the component that calls useEditor is inside of `EditorContent` and not just inside of `EditorRoot` as shown in the docs. At least for me.

**Comment by akdeb** [comment]
@jonkurtis did you figure out a workaround?
