### ISSUE TITLE
Custom headers for completion api.

### ISSUE THREAD

**Issue by abhiabhijit** [steven-tey/novel#167]
I need to pass csrf token to the api endpoint in the useCompletion function. Can you please add support to pass headers?

Something like

`<Editor completionApiHeaders={headers} />`

I added a new header prop named completionApiheaders in my forked novel project, built it and replaced dist folder in my node_modules->novel folder. but still, it didnt work for me.

Can anyone please help me?

**Comment by steven-tey** [comment]
Hey! You should be able to do this directly inside your own API route since `novel` only invokes the API route :)

Related to the reason why https://github.com/steven-tey/novel/pull/181 was closed
