### ISSUE TITLE
Add variety of different types of formats

### ISSUE THREAD

**Issue by ashrafchowdury** [steven-tey/novel#17]
## Description 

The current text editor does not support a variety of different types of formats, which limits its usability. For example, it does not support code blocks, block quotes, or tables. Adding these formats would make the text editor more versatile and useful for a wider range of tasks.

**We can add:**

* CodeBlock
* BlockQuote
* Horizontal Rule
* Tables etc

**Comment by ashrafchowdury** [comment]
I can add more useable formats to the editor, if you like the idea you can assign me to do this work.

**Comment by steven-tey** [comment]
`CodeBlock`, `BlockQuote` and `HorizontalRule` are actually all supported! 

Would love to add tables though – feel free to PR! You can use [Tiptap tables](https://tiptap.dev/examples/tables) as reference but would love to make it have a similar UX as Notion's tables (hover to add rows/tables)

![CleanShot 2023-06-19 at 15 40 55](https://github.com/steven-tey/novel/assets/28986134/c5557a1c-61fc-45b9-89be-6d56f73c3f7c)

**Comment by ashrafchowdury** [comment]
I would love to create the **Notion-like table**. you can assign me to this issue.

The `CodeBlock`, `BlockQuote`, `HorizontalRule` are not listed on the selectors that's why I thought those are not implemented yet.

**Comment by ashrafchowdury** [comment]
Hey @steven-tey a quick question for you, I have to table design mockup for the editor, which one do you think is the best for users 👇


**This is clean and very much user-friendly.**
![image](https://github.com/steven-tey/novel/assets/87828904/5324a054-5633-4031-b293-e43451960615)

**This is a bit complex and requires a lot of functionalities.**
![image](https://github.com/steven-tey/novel/assets/87828904/3793ad24-39fd-44c3-bfcb-90eecc7b9d66)

**Comment by steven-tey** [comment]
@ashrafchowdury definitely the first one! Let's use the simple table in Notion as reference! :)

![CleanShot 2023-06-22 at 10 51 35](https://github.com/steven-tey/novel/assets/28986134/9b6ee1f7-c262-44c2-824d-6149a2741f92)

**Comment by steven-tey** [comment]
Quick update: Codeblock and blockquote have been added to slash menu in https://github.com/steven-tey/novel/pull/35

**Comment by ashrafchowdury** [comment]
Hey @steven-tey 👋

I created the **Table format and implemented it in the editor**, now I want feedback from you to before making the pr-request



https://github.com/steven-tey/novel/assets/87828904/afce2907-6843-4f59-9280-d01a187b0de1


**I have added:**

* Adding & deleting Column
* Adding & deleting Row
* Delete Table
* A mune for the table

**Comment by steven-tey** [comment]
@ashrafchowdury looks incredible 🤯 only thing I can think of is the icons might not be clear enough 😅

Also, would it be possible to rearrange the columns? 

Feel free to go ahead and add that PR and we can iterate on this! 

P.S.: what does "a mune for the table" mean?

**Comment by mmailaender** [comment]
@steven-tey, @ashrafchowdury  some suggestions for the icons:

![image](https://github.com/steven-tey/novel/assets/87228994/6d3c15fd-d8a3-4004-915a-7e99296620e7)
![image](https://github.com/steven-tey/novel/assets/87228994/b82f91d7-deac-4a52-9be3-b03e82d79092)
![image](https://github.com/steven-tey/novel/assets/87228994/60037628-a7c1-4775-b44d-2c5d3f1aa387)
![image](https://github.com/steven-tey/novel/assets/87228994/25ddf0cb-8299-4eeb-94b2-513f678a99b4)
![image](https://github.com/steven-tey/novel/assets/87228994/fcc17e66-26c6-4290-b76e-0813528c5add)
![image](https://github.com/steven-tey/novel/assets/87228994/f41d9d98-3ec0-4adb-9490-28fb404fefb6)

If you like them, I provide the SVG code.

**Comment by ashrafchowdury** [comment]
@mmailaender we are using the lucide icon library for the project icons 👍

**Comment by mmailaender** [comment]
> @mmailaender we are using the lucide icon library for the project icons 👍

Except from the first icon they are self crafted, because we had the same situation that @steven-tey talks about, that e.g. the lucid icons don't have expressive icons for table.

**Comment by mmailaender** [comment]
After thinking about the first approach, I think I'm not so happy with it. I would prefer a more context-aware table like e.g. Figma Tables (The icons would be also simpler)

https://github.com/steven-tey/novel/assets/87228994/1d56ed93-f06f-413b-b63a-0d05816db5eb
(The table column `delete` in the video is happening with keyboard shortcut)

What do you think?

**Comment by steven-tey** [comment]
@mmailaender that one looks incredible! Similar concept to Notion's implementation, which I really like <picture data-single-emoji=":amazing-rainbow:" title=":amazing-rainbow:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/amazing-rainbow/a719e1c9d03c7e75.gif" alt=":amazing-rainbow:" align="absmiddle"></picture>

**Comment by ashrafchowdury** [comment]
That looks really clean & awesome 😘

If we wanted to add that type of table then we have to spend a bit of time to build it from scratch.
