### ISSUE TITLE
localstorage value is priortised over default value

### ISSUE THREAD

**Issue by thakurthegr8** [steven-tey/novel#170]
Im fetching the novel content data from the api and populating the editor but editor is picking the value from localstorage.

**Comment by steven-tey** [comment]
Apologies for the delay here! 

`novel@0.1.21` now has a new `disableLocalStorage` prop that lets you disable reading / writing content from local storage!

Check out the release: https://github.com/steven-tey/novel/releases/tag/0.1.21
