### ISSUE TITLE
Make `OPENAI_API_KEY` optional

### ISSUE THREAD

**Issue by perryraskin** [steven-tey/novel#174]
Would love to use Novel as a non-AI-autocomplete text editor, since of course bc it's gorgeous. Can the `OPENAI_API_KEY` be made optional? If it is already optional, perhaps the ReadMe can indicate as such and how to properly skip it

**Comment by sergeysova** [comment]
I made full featured fork due to the same issue

https://github.com/sergeysova/craft

**Comment by leowilkin** [comment]
Hey @perryraskin. You can leave the `OPENAI_API_KEY` field with a random string and AI features are 'disabled'.

**Comment by andrewdoro** [comment]
With the new update, AI features are disabled by default
https://novel.sh/docs/quickstart#anatomy
