### ISSUE TITLE
Use this repo instead of npm?

### ISSUE THREAD

**Issue by Michota** [steven-tey/novel#175]
Hello. How do i use this repository instead of `npm i novel`?

I wanted to clone this repository so i would cherry-pick commits from different pull-requestes, so my novel node_module would be updated with solutions provided by others, and this way i wont need to depend on updates provided by @steven-tey (creator of novel).

But i don't know how to properly import from cloned repo.
I want it to be similiar to npm package, so import would work just like this
`import { Editor } from "novel"`.

Sorry if this question seems stupid, but im a begginer.

**Comment by mkrkelj1** [comment]
It’s not a stupid question — Novel extends the TipTap editor.  You can find the implementation inside `packages/core`.  Dependencies you need to install are in `packages/core/package.json` and the editor itself is in `packages/core/src/ui/editor/index.tsx`. Happy hacking.

**Comment by steven-tey** [comment]
Thanks for responding here @mkrkelj1!
