### ISSUE TITLE
Live collaboration 

### ISSUE THREAD

**Issue by mohanadkandil** [steven-tey/novel#179]
A live collaboration feature by sharing doc's link. 

I can start working on this one. It can be done fast by [PartyKit](https://www.partykit.io/) or [Liveblocks](https://liveblocks.io/), and anyone feel free if you have any other recommendations.

**Comment by jguddas** [comment]
https://github.com/steven-tey/novel/pull/18

**Comment by steven-tey** [comment]
This is not planned for now, but we might revisit in the future. Thanks though!
