### ISSUE TITLE
Issue: Prevent Novel Editor from Overwriting Tailwind CSS Styles #184

### ISSUE THREAD

**Issue by felipebarcelospro** [steven-tey/novel#185]
Hi everyone,

I've noticed an issue with the Novel Editor that's causing it to overwrite Tailwind CSS styles in my projects. This is causing some unexpected behavior and conflicts.

I believe it would be beneficial to find a solution to prevent this overwriting. It could improve the overall compatibility and usability of Novel Editor with projects using Tailwind CSS.

I'd appreciate your thoughts and suggestions on how best to tackle this issue.

**Comment by sebszocinski** [comment]
We have the same issue with our app and using shadcn/ui. Also dark mode doesn't play nicely because shadcn/ui uses "dark" and "light" classes on html and Novel uses "dark-theme" and "light-theme"

**Comment by notjustinshaw** [comment]
you just need to update your config

see: https://github.com/steven-tey/novel/blob/main/apps/web/app/providers.tsx

**Comment by datarm-rs** [comment]
PR #161 will fix this, I think. Not sure the progress on that though. It's been sitting waiting for integration for about 3 weeks now. @steven-tey
