### ISSUE TITLE
drag upload image not show image uploading

### ISSUE THREAD

**Issue by ghost** [steven-tey/novel#197]
hi @steven-tey , i see this issue in novel.sh  
![image](https://github.com/steven-tey/novel/assets/144557310/19330616-b9c2-4e83-a22e-874831030d04)
![image](https://github.com/steven-tey/novel/assets/144557310/18c05a60-c8d4-4361-8bb8-282e02a096b4)

**Comment by steven-tey** [comment]
Should be fixed by #172
