### ISSUE TITLE
default value not getting rendered

### ISSUE THREAD

**Issue by Vivek377** [steven-tey/novel#198]
I've been trying adding default value to my editor but it doesn't seem to be getting rendered.

First I store my typed data in db and fetch it back to render it as default value so I can see it again any time I login to my project, but the problem is that it does not show the default value on my screen.

`<Editor
      defaultValue={value}
      onDebouncedUpdate={(data) => handleSendMessage(data.getJSON())}
      debounceDuration={3000}
      disableLocalStorage={true}
    />`

value is a state value.

**Comment by solanovisitor** [comment]
Same here!

```
      <Editor
        defaultValue={editorContent} // Set the default value
        onUpdate={handleUpdate} // Attach onUpdate handler
        onDebouncedUpdate={handleDebouncedUpdate} // Attach debounced update handler
        debounceDuration={1000} /// 1 second debounce time
      />
```

**Comment by mathiasrscom** [comment]
Hey! I had it working if I added a useEffect and a useState for my data. My data comes from React Query, hence why I have  `useContentByContentIdEdit`, so you can ignore it and adjust it to how you get your data. One thing that I found out was, that I had to add a key prop to the editor. You could try that too, so that React knows when yo rerender a component. 

Here is an example from my app:

```js
import { useEffect, useState } from "react"

// Queries
import useContentByContentIdEdit from "@/actions/queries/content/useContentByContentIdEdit"

export default function Page() {
const [editorContent, setEditorContent] = useState("")

const { data: content, isLoading } = useContentByContentIdEdit(contentId)

useEffect(() => {
  if (contnet) {
    setEditorContent(content)
  }
}, [content])

return (
   <div className="relative w-full">
      <Editor
        key={locale.code}
        onDebouncedUpdate={handleEditorUpdate}
        debounceDuration={750}
        disableLocalStorage
        defaultValue={editorContent || ""}
        className="-mt-10"
      />
   </div>
)
```

**Comment by akaizn-junior** [comment]
@Vivek377 I thought I was alone in this one. But as @mathiasrscom pointed out, you need to re-render the component with a `key` prop. This way you repaint the Editor after fetching your data.

**Comment by akaizn-junior** [comment]
@steven-tey what are your thoughts on rendering the editor only after default value is "something". In the case for waiting for data to be fulfilled until we can render the Editor without using the `key` prop.

**Comment by BereCephas** [comment]
i discover that you just need that tou just need to acces to the ".content"  property of your Json file.
`"use client";
import { Editor } from "novel";
import defaultPage from "../test.json";

export default function Page() {

  return (
    <div className="relative w-full">
      <Editor
        disableLocalStorage
        defaultValue={defaultPage.content}
        className="-mt-10"
      />
    </div>
  );
}
`

**Comment by BereCephas** [comment]
i discover that you just need that tou just need to acces to the ".content" property of your Json file.
`"use client";
import { Editor } from "novel";
import defaultPage from "../test.json";
export default function Page() {
return (
);
}`

**Comment by andrewdoro** [comment]
Hey the new editor has an `intialContent` prompt, that is only set once. If you want to change the content outside the editor after you can save your own editor instance with onCreate
```tsx
import {
  Editor,
  EditorContent,
} from "novel";

const [editor, setEditor] = useState<Editor|null>(null)

 useEffect(() => {
   if(!editor) return
   editor.commands.setContent(newContent)
  }, [newContent]);

 
<EditorContent
         onCreate={({editor})=>setEditor(editor)}
         initialContent={initialContent}
        >
```


https://novel.sh/docs/components/editor-content
