### ISSUE TITLE
How to handle auth?

### ISSUE THREAD

**Issue by emil14** [steven-tey/novel#200]
[Here](https://github.com/steven-tey/novel/blob/main/packages/core/src/ui/editor/plugins/upload-images.tsx#L117C1-L117C1) we can see than Novel calls `fetch` without ability to insert custom headers. Same goes for 'api/generate' logic. How one must implement auth?

**Comment by tunogya** [comment]
I use Auth0 in NextJS, so i can do this at Edge environment:

```
import { getSession } from "@auth0/nextjs-auth0/edge";

export const runtime = "edge";

const { user } = await getSession();
```

**Comment by andrewdoro** [comment]
This is not really related to Novel, I've also disabled the AI feature for now. After I finish my work it would be opt-in and fully customizable.
