### ISSUE TITLE
Issue: novel styles are overwriting other styles (NOT TAILWIND)

### ISSUE THREAD

**Issue by Michota** [steven-tey/novel#201]
CSS from Novel has an impact on other parts of my app. 

Styling like will disable my styling on these elements.
`h1,
h2,
h3,
h4,
h5,
h6 {
  font-size: inherit;
  font-weight: inherit;
}`

Obviously other tags, like `input` will also change styling. Im not talking about #184 #185 #128 , but about plain CSS (and styled components)!

**Comment by yongyi520** [comment]
I second this

Looks like the tailwind element got re-loaded again after you display the editors

Then it just overrides the settings I had before with var(--border) for example

![Screenshot 2023-10-11 at 17 51 26](https://github.com/steven-tey/novel/assets/10789851/019542d1-c3b8-4db4-a51b-2c89fb045912)

**Comment by dooart** [comment]
i just solved it by forking the project and using this plugin: https://github.com/Roman86/tailwindcss-scoped-preflight

**Comment by andrewdoro** [comment]
Novel now exports unstyled components by default
https://novel.sh/docs/quickstart#anatomy
