### ISSUE TITLE
Hi, i am beginner here, is there any chance to disabled AI generator?

### ISSUE THREAD

**Issue by Adiyasa26** [steven-tey/novel#204]

**Comment by leowilkin** [comment]
Hey @Adiyasa26. You can disable to the AI Generator by putting in a random string in the OPENAI_API_KEY Environment Variable, and if the AI generator is called it just responds with "error, no api key".

Hope that helps, and if not please reply.

**Comment by sangdth** [comment]
This is a very simple wrapper of Tiptap editor combine with OpenAI API, so if you just need the simple editor, please reach https://github.com/ueberdosis/tiptap

**Comment by andrewdoro** [comment]
Newer version doesn't have the AI feature active by default. 
https://novel.sh/docs/quickstart#anatomy
