### ISSUE TITLE
Issues with Next/Tailwind project.

### ISSUE THREAD

**Issue by ozamamurzleen** [steven-tey/novel#209]
We are trying to use the editor in app. BUT its overriding all our styles.
Can you suggest what can we do to avoid conflicting with our styles?

**Comment by sbusso** [comment]
Just trying to integrate the Novel package in a Next app and I have the same issue here. It looks like prefix styles are not preventing main styles from being overridden.

**Comment by ozamamurzleen** [comment]
@sbusso Yes. Thanks having same issues.

**Comment by Ankur-Datta-4** [comment]
I'm still facing this issue.
Is it sorted>?

**Comment by justinkook** [comment]
Not yet sorted. I'm still having issues with the styles being overwritten.

**Comment by josealvarez97** [comment]
@justinkook Did you come with an effective workaround? Whenever I import a component using novel into another component, I get my styles from `globals.css` (not tailwind) overwritten, e..g, default color of `a` tags
