### ISSUE TITLE
How to stop scrolling behaviour?

### ISSUE THREAD

**Issue by okandavut** [steven-tey/novel#212]
Hi, thanks for this editor and it's really good.

I have a question that editor is scrolling automatically to bottom and I just wanted to stop this behaviour is there any option for that? Do you have any idea?

**Comment by arthureberledev** [comment]
This PR https://github.com/steven-tey/novel/pull/199 will fix it

**Comment by TheAlphamerc** [comment]
Waiting for the release of this fix 🤞🏼
