### ISSUE TITLE
Stale data in localstorage

### ISSUE THREAD

**Issue by hsiez** [steven-tey/novel#216]
Hello there. First and foremost, I'm really enjoying novel. Best plug and play RTE. Major props.

**Issue**
There is a delay in the data stored in localstorage compared to the text shown on the editor in the UI.
<img width="1303" alt="Screen Shot 2023-10-16 at 3 11 02 PM" src="https://github.com/steven-tey/novel/assets/79492916/58743bac-c25c-41ea-93e0-aa7475258bda">

The screenshot shows the console output from a function passed thru to the editor via the onUpdate prop.

**Why this matters to me**
I created a submit button that sends the text to my DB. I'd like to disable the button if the editor is empty. My current solution is to manage this via a state var handled by the onUpdate function. On every update, it will check if editor is empty and change `areButtonsDisabled` accordingly. If the data in localstorage is stale, this solution gets buggy. 

** Questions **
Is using `onDebouncedUpdate` and setting `debounceDuration` to 0 the same as just using onUpdate?
How would you handle a component dependent on the Novel editor?

**Comment by andrewdoro** [comment]
You can now opt-out completely of the local storage
Just follow this guide to have it setup.
https://novel.sh/docs/guides/tailwind/setup

**Comment by Praneeth-Pike** [comment]
> You can now opt-out completely of the local storage
> Just follow this guide to have it setup.
> https://novel.sh/docs/guides/tailwind/setup

@andrewdoro Hey I'm running into the same issue. And I think you've provided the wrong link here. I tried to look in the documentation but I can't find it.
