### ISSUE TITLE
MUI styles are getting overrided with Editor styles

### ISSUE THREAD

**Issue by kareemCapsuleHub** [steven-tey/novel#219]
In Next.js, I am dynamically rendering a novel editor. After the rendering is complete, the MUI styles are getting effected, and they are not working as expected. Has anyone else experienced this issue?

**Comment by pcriadoperez** [comment]
Hi, running into the same issue. In our case it's the css of button that tailwinds generates. Could this be fixed by adding a prefix to all tailwinds in the novel package?

**Comment by faisalsayed10** [comment]
+1. same issue. tailwind button styles are getting overriden

**Comment by K-S-Code** [comment]
+1. Button styles are being overwritten (transparent backgrounds)

**Comment by AdytZZa22** [comment]
+1. Using shadcn UI, same issue - button styles are being overwritten

**Comment by jotanarciso** [comment]
same here.

**Comment by srizvi** [comment]
I'm experiencing the same with shadcn.

**Comment by tiavina-mika** [comment]
+1, MUI button and dialog styles ared changed

**Comment by hari-bhandari** [comment]
+1

**Comment by TsarPrince** [comment]
+1

**Comment by andrewdoro** [comment]
https://novel.sh/docs/quickstart#anatomy novel now exports unstyled components, you can fully style them on your end now or use the guide for tailwind
