### ISSUE TITLE
Thinking about adding a dark mode?

### ISSUE THREAD

**Issue by Azad-Aihub** [steven-tey/novel#22]
Is it possible to consider adding a dark mode switch, which could be great for writers used to writing in dark mode?

**Comment by notjustinshaw** [comment]
I've been able to implement dark-mode in tailwind with the typography plugin with just `prose dark:prose-invert`.

**Comment by steven-tey** [comment]
@notjustinshaw 👀 that's awesome! Feel free to make a PR to add dark mode to Novel! 😄

**Comment by notjustinshaw** [comment]
![Screen Shot 2023-06-22 at 10 58 00 PM](https://github.com/steven-tey/novel/assets/46334750/53f0b1b5-62d6-44ee-90ad-a99d9a6dd7db)

**Comment by Dhravya** [comment]
I could get darkmode to work, I'm using cookies to store current mode 

![GIF demo](https://i.dhr.wtf/r/7d473.gif)

**Comment by sreehari2003** [comment]
> I could get darkmode to work, I'm using cookies to store current mode
> 
> ![GIF demo](https://camo.githubusercontent.com/606b736c9d90cb862792b0a3288334177f6a73128c275a25b0494938a535aa9d/68747470733a2f2f692e6468722e7774662f722f37643437332e676966) [ ![GIF demo](https://camo.githubusercontent.com/606b736c9d90cb862792b0a3288334177f6a73128c275a25b0494938a535aa9d/68747470733a2f2f692e6468722e7774662f722f37643437332e676966) ](https://camo.githubusercontent.com/606b736c9d90cb862792b0a3288334177f6a73128c275a25b0494938a535aa9d/68747470733a2f2f692e6468722e7774662f722f37643437332e676966) [ ](https://camo.githubusercontent.com/606b736c9d90cb862792b0a3288334177f6a73128c275a25b0494938a535aa9d/68747470733a2f2f692e6468722e7774662f722f37643437332e676966)

this dark mode ui looks in consistent , that toggle button size is large , continue writing icon missing etc  also y store in cookie  ? i think it is better to store the theme state in local storage than cookies

**Comment by Dhravya** [comment]
Yeah, I fixed all the issues you mentioned in the above commits already. 😁

Why cookies: it's hard to manage global state in server components, local storage could be done but this was a very straightforward approach, so I went with it

**Comment by Dhravya** [comment]
Yeah, I fixed all the issues you mentioned in the above commits already. 😁

Why cookies: it's hard to manage global state in server components, local storage could be done but this was a very straightforward approach, so I went with it

**Comment by Amsalak** [comment]
Ne olduğunu anlamayan yine ben

**Comment by steven-tey** [comment]
Dark mode is now live!! #80
