### ISSUE TITLE
Re-export EditorClass

### ISSUE THREAD

**Issue by sangdth** [steven-tey/novel#220]
First of all thanks for making the Novel, it works great with just a few line of codes!

Currently I want to use this way `<Editor onUpdate={handleUpdate} />`, so I can make the handler more complex without messing with the jsx. But in order to use it I have to install `@tiptap/core` again just to have the `Editor` class.

I checked the source of Novel and saw we already have `EditorClass`, just wonder should we re-export those types so customers don't need to re-install `tiptap`? My ideal is to keep the tiptap under `novel` as much as possible.

Thanks.

**Comment by andrewdoro** [comment]
https://novel.sh/docs/components/utils/use-editor 
or you can save your instance with onCreate callback 
https://novel.sh/docs/components/editor-content
