### ISSUE TITLE
Warning duplicated ['image']

### ISSUE THREAD

**Issue by sangdth** [steven-tey/novel#221]
I have this warning:
```
[tiptap warn]: Duplicate extension names found: ['image']. This can lead to issues. ...
```
<img width="634" alt="Screenshot 2023-10-18 at 18 44 36" src="https://github.com/steven-tey/novel/assets/1083478/2d411f83-1b2b-4895-a949-580e12094927">

I guess it's because the `UpdatedImage` extended from the `@tiptap/extension-image` and both have 
```
  name: 'image',
```
which causes the warning?

**Comment by mathiasrscom** [comment]
I see the same thing.

**Comment by tiavina-mika** [comment]
+1

**Comment by JimmyLv** [comment]
+1

**Comment by Moumen-io** [comment]
I am receiving this error
