### ISSUE TITLE
Not able to set HTML in `defaultValue`

### ISSUE THREAD

**Issue by tksumanth1994** [steven-tey/novel#223]
In tiptap, `setContent` can be used with HTML.

<img width="784" alt="image" src="https://github.com/steven-tey/novel/assets/4353562/834091a1-9a9b-4691-ade7-b9d28beb0930">

But, in Novel, it renders as a string when I set `defaultValue` as HTML - `<p>Hello</p>`.

This code

```
<Editor
    disableLocalStorage={true}
    defaultValue="<p>Hello</p>"
/>
```

renders this

<img width="540" alt="image" src="https://github.com/steven-tey/novel/assets/4353562/6c7909fe-ad75-40cf-8b45-3745126ae2d2">

Is there a workaround for this?

**Comment by tiniscule** [comment]
I'm also hitting this - if you look at where the code sets the content, it's just calling `setContent` directly in tiptap.  Looking upstream I don't see anyone reporting it, but I'm wondering if this is a regression there

**Comment by tiniscule** [comment]
Actually - found it.  Novel uses the `tiptap-markdown` extension, which overrides the `setContent` function with its own.  This line here sets HTML support to false, but I'm not sure why.   Swapping this to true enables support for markdown.  I don't want to submit a PR for this as I'm not sure why it's disabled in the first place.  I've enabled it in my local copy.

https://github.com/steven-tey/novel/blob/b4526fc63175caed02bdbfbee490e87b3466dd1c/packages/core/src/ui/editor/extensions/index.tsx#L137-L140

**Comment by swarajbachu** [comment]
@steven-tey  this error isnt solved yet

**Comment by andrewdoro** [comment]
As a workaround for this I'll add PR so you can configure/remove the Markdown extension

**Comment by bouceka** [comment]
Any update on this one? Does Novel have any other solution for this?

**Comment by bouceka** [comment]
I tried to find a solution as the Tiptap editor allows you to set content with either JSONContent or HTMLContent 
<img width="612" alt="Screenshot 2024-02-24 at 11 05 13 AM" src="https://github.com/steven-tey/novel/assets/49728880/aab65737-1590-42d5-bad7-ed056351fa24">
Novel does not allow that, or at least not by default 
<img width="594" alt="Screenshot 2024-02-24 at 11 05 36 AM" src="https://github.com/steven-tey/novel/assets/49728880/d8a38fb1-3799-432d-97c7-83627b91a7e3">
Unfortunately, even though I changed the markdown and configured the HTML to true, it still does not work for me. If anyone has a neat solution, please let me know.

**Comment by SemperFortis** [comment]
+1 on this issue. This seems to be a very important feature missing which is supposed to be supported out of the box. I would suggest exposing lower level APIs from TipTap so we can hook into this directly. @andrewdoro

**Comment by lh15** [comment]
+1 does anyone have a solution for passing html? Thanks

**Comment by amang06** [comment]
this worked for me, I am able to set html by converting it to json. However, the style won't apply automatically

```
import { generateJSON } from "@tiptap/html";

	useEffect(() => {
		const htmlString: string = `<h1><strong>This is strong</strong></h1>
		<h2><b>And this</b></h2>
		<h3 style="font-weight: bold">This as well</h3>
		<p>Oh! and this</p>
		<p style="color: #E00000">Cool!</p>`;
		console.log(generateJSON(htmlString, extensions));
		setInitialContent(generateJSON(htmlString, extensions));
	}, []);
```

We need to handle these style using global attributes and create a custom extension as mentioned [here](https://tiptap.dev/docs/editor/guide/custom-extensions#global-attributes)

below is an example i used to apply colors and passed it as extension

```
import { Extension } from "@tiptap/core";

const style = Extension.create({
	addGlobalAttributes() {
		return [
			{
				// Extend the following extensions
				types: ["heading", "paragraph"],
				// … with those attributes
				attributes: {
					textAlign: {
						default: "left",
						renderHTML: (attributes) => ({
							style: `text-align: ${attributes.textAlign}`,
						}),
						parseHTML: (element) => element.style.textAlign || "left",
					},
					color: {
						default: "black",
						renderHTML: (attributes) => ({
							style: `color: ${attributes.color}`,
						}),
						parseHTML: (element) => element.style.color || "black",
					},
				},
			},
		];
	},
}); 
```

**Comment by lh15** [comment]
@amang06 Did you have to add every possible HTML element to extensions?

My concern is that if I miss something, it'll break the original html.

I am using this as a wordpress post editor

**Comment by amang06** [comment]
@lh15 I am afraid yes. Refer [this](https://github.com/ueberdosis/tiptap/issues/331)
I also share your concern, I guess we are better off storing both json and html at this point.

**Comment by bouceka** [comment]
This is how I solved it. I store both HTML and JSON objects.

**Comment by lh15** [comment]
Can you explain how it helps to store both the html and json?

Say I load in html from a wordpress post, once I parse it into tiptap, I lose data. 

I can't really "recover" the missing data.

**Comment by Prathamesh-Dukare** [comment]
Tiptap provided the api to convert html into tip-tap json. [See here ](https://tiptap.dev/docs/editor/api/utilities/html#generate-html-from-json)

### Uses
```
import { generateJSON } from "@tiptap/html";

import Document from "@tiptap/extension-document";
import Paragraph from "@tiptap/extension-paragraph";
import Text from "@tiptap/extension-text";
import CodeBlock from "@tiptap/extension-code-block"; 


const html = `<h2>Introducing salman</h2>`
const json = generateJSON(html, [Document, Paragraph, Text, CodeBlock]); // import and add more extensions as needed
console.log(json);
