### ISSUE TITLE
OpenAI Issue - Failed to fetch the chat response

### ISSUE THREAD

**Issue by ahmedrizwan239** [steven-tey/novel#226]
![image](https://github.com/steven-tey/novel/assets/112283994/77055840-648f-4ecd-a5ff-152b435b265c)

I'm facing this issue, since I added my own OPENAI_API_KEY. I'm not using a paid version of gpt, I just simply generated a key and added it to environment variables while deploying. 

Do I need to have credits in order to resolve this? Please let me know. 

Thanks!

**Comment by andrewdoro** [comment]
Hey I think you need credits for it to work. An alternative is using ollama locally. (Keep in mind the library had a breaking update recently and the AI featured was disabled until I can write a more detailed guide for it.
https://ollama.com/blog/openai-compatibility
