### ISSUE TITLE
Named export 'Markdown' not found

### ISSUE THREAD

**Issue by technotip** [steven-tey/novel#231]
One of the dependencies `tiptap-markdown` has issues working with remixjs.
It'll be fixed in v0.8.4. https://github.com/aguingand/tiptap-markdown/issues/47

Please make sure to update the dependency for novel.sh

I'm very eager to start using novel.sh in my remixjs app. Looking forward to it.

**Comment by andrewdoro** [comment]
fixed by #295
Release package [0.2.4](https://www.npmjs.com/package/novel/v/0.2.4)
