### ISSUE TITLE
help regarding how to contribute

### ISSUE THREAD

**Issue by Elon-Mask12** [steven-tey/novel#236]
I'm new to turborepo, tsup, building npm packages in general. 
I was trynna fix few issues, but then everytime i make any changes to any file inside the packages directory, the whole app crashes: 
![image](https://github.com/steven-tey/novel/assets/96902442/89f525e5-5818-4373-b6f4-3bc9c35a4dd5)

I believe this happens cause of typescript regenerating the js files on filechange. But this makes it impossible to use, is there anything im missing. can someone pls guide me on how to set it up?
thanks.

**Comment by Elon-Mask12** [comment]
Little help please? @steven-tey

**Comment by Elon-Mask12** [comment]
umm any news?

**Comment by Elon-Mask12** [comment]
wdym completed?

**Comment by andrewdoro** [comment]
There were a lot of breaking changes, recently try to do a sync with the new changes, and tell me if you still have problems. I am trying to cleanup the issues as the code has changed a lot.
