### ISSUE TITLE
Can you add your own styles to the editor?

### ISSUE THREAD

**Issue by mansidak** [steven-tey/novel#245]
Just started using Novel locally and was curious if it's possible to tweak the styles to match your app?

The globals.css file doesn't seem to have a lot of info. I'm probably not looking at the right place but curious if there are any more convenient ways to change the look and feel of the slash drop down menu, the highlight bubble menu etc etc. 

<img width="409" alt="Screenshot 2023-11-22 at 10 12 58 AM" src="https://github.com/steven-tey/novel/assets/51833970/501d0b25-078e-4a1e-b9c7-5605943ae78c">

**Comment by andrewdoro** [comment]
https://novel.sh/docs/quickstart you can do this now
