### ISSUE TITLE
Weird UI

### ISSUE THREAD

**Issue by AeroXi** [steven-tey/novel#25]
<img width="1144" alt="image" src="https://github.com/steven-tey/novel/assets/31943024/344bfd2e-51f3-4e09-9dbb-cdaa1ed646a3">

**Comment by steven-tey** [comment]
What browser are you using?

**Comment by acubesa** [comment]
Happening the same to me with lists. I'm using safari @steven-tey

**Comment by steven-tey** [comment]
Ooooh I can repro <picture data-single-emoji=":mind-blown-telegram:" title=":mind-blown-telegram:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/mind-blown-telegram/8da1ff249e3eff45.gif" alt=":mind-blown-telegram:" align="absmiddle"></picture> this is super weird, lemme look into it

**Comment by steven-tey** [comment]
Still couldn't figure it out – looks like a weird Safari bug :(

**Comment by acubesa** [comment]
@steven-tey how about setting the width of that container to the same width as the editor? It would be a workaround to hide this UI bug

**Comment by steven-tey** [comment]
@acubesa sounds promising! Wanna PR? 👀

**Comment by acubesa** [comment]
@steven-tey Will do 🙌🏻

**Comment by z4nr34l** [comment]
@acubesa please ping me when you will be fixing it, I will add a few lines to your PR - if we clean component's styles a bit this issue will not exists.

@steven-tey What you think about migration of this demo to shadcn-ui? :D

**Comment by acubesa** [comment]
@z4nr34l feel free to go ahead and make the PR - haven't been able to allocate some time here 😅 

+1 to shadcn ui btw

**Comment by z4nr34l** [comment]
Update: Demo UI/UX layout is almost ready, I'm currently just making it perfect.

<img width="1324" alt="image" src="https://github.com/steven-tey/novel/assets/5320734/f534c546-7aff-43e2-967a-b2f3f7f6858c">

I will add PR as soon as I would have it done 100% - maybe even today :D

**Comment by z4nr34l** [comment]
PR is waiting :D

#91
