### ISSUE TITLE
No option to add API key

### ISSUE THREAD

**Issue by shinebarbhuiya** [steven-tey/novel#262]
I installed novel using npm for my next js project - npm i novel but where should I set the OpenAI key? Totally clueless. The docs is super simple and many main things are not mentioned.

**Comment by marcushohlbein** [comment]
I think you have to set your key in the `.env` as `OPENAI_API_KEY`

**Comment by janzheng** [comment]
you need to put the `.env` file in `apps/web/.env` instead of root since it's a turborepo project (this was new to me too)
