### ISSUE TITLE
Vulnerabilities - 6 vulnerabilities (3 low, 3 moderate)

### ISSUE THREAD

**Issue by Beewong1998** [steven-tey/novel#270]
Hey Steven, I am trying to use this rich text editor for my company but at the moment there's some vulnerabilities shown after installing Novel. When I try npm audit fix it makes it worse and introduces 5 more severe vulnerabilities. Will this be fixed soon? Thank you!

**Comment by andrewdoro** [comment]
I've updated the deps, there shouldn't be any severe vulnerabilities. Just write me if you have other problems.
