### ISSUE TITLE
Tailwind styles being reset when adding Novel as an npm package

### ISSUE THREAD

**Issue by elie222** [steven-tey/novel#281]
The button is white because Novel's Tailwind is resetting the styles:
![CleanShot 2024-02-05 at 21 01 14@2x](https://github.com/steven-tey/novel/assets/3090527/d03fdd3c-f378-43ba-b455-7e8f2c1b0ebf)

I've seen a lot of PRs related to styling but none about this specifically. Would love a quick fix.

**Comment by AmitGurbani** [comment]
Any update on this? Facing same problem with MUI.

**Comment by andrewdoro** [comment]
https://novel.sh/docs/introduction novel now exports unstyled components, you can style it for your specific use case
