### ISSUE TITLE
AI not showing ++ or slash menu

### ISSUE THREAD

**Issue by hscale** [steven-tey/novel#291]

**Comment by andrewdoro** [comment]
Hey I disabled AI features until I can revamp the component, I'll add some info explaining that on the demo page.

**Comment by aligajani** [comment]
@andrewdoro  How can I we add it back? Any quick fix

**Comment by chinnuu05** [comment]
> @andrewdoro How can I we add it back? Any quick fix

You can reset --HARD one of Steven's old commits

**Comment by andrewdoro** [comment]
This PR will add a guide about using AI
You can also already test it here. 
[Vercel](https://novel-r5wzv908o-elegance.vercel.app/)
https://github.com/steven-tey/novel/pull/297
