### ISSUE TITLE
bug: Image can't be resized 

### ISSUE THREAD

**Issue by phukon** [steven-tey/novel#309]
### Provide environment information

.

### Describe the bug

The issue arises where images can only be resized once within Novel's web app. Additionally, newly added images cannot be resized at all.

### Link to reproduction

https://novel.sh/

### To reproduce

- Open Novel's web app.
- Attempt to resize an existing image. Note that after resizing once, the image becomes unresizable.
- Add a new image to the app.
- Try to resize the newly added image. Observe that resizing is not possible.

### Additional information

https://github.com/steven-tey/novel/assets/60285613/1e389fbd-6815-405f-9198-039812502a04

**Comment by Sloosmore** [comment]
Also note that newly added images cannot be moved!

**Comment by andrewdoro** [comment]
should be fixed now by #315
