### ISSUE TITLE
As a user I need to be able to reset text formatting and indentation

### ISSUE THREAD

**Issue by aMacDawg** [steven-tey/novel#31]
**Expected outcome:** as a user of Novel's UI, I need text editing functionality that enables me to 'reset' text body indentation, particularly when creating a new line _after_ a numbered or unordered list

**Current outcome**: When create a new line _after_ a numbered or unordered list, I am able to delete the unwanted bullet point by hitting `backspace` however, I am not able to reset the indentation to be a primary body of text, either by hitting backspace again (which just deletes the `new line` and positions the new paragraph as a body within the list item) _or_ by hitting `return` key which just creates a new line at the same (unwanted) indentation formatting

![Screenshot 2023-06-20 at 6 39 58 PM](https://github.com/steven-tey/novel/assets/2131091/9fadde7d-153b-4436-86bf-a01d702a131e)

**Comment by ashrafchowdury** [comment]
Hey @aMacDawg, you have to **hit the enter key twice to remove the ordered or number list indentation**, and then you will get a new line for the paragraph.

**Comment by steven-tey** [comment]
@ashrafchowdury is right – double enter is how you can escape the list indentation.

However, Notion allows you to escape it with a backspace too, so ideally we'd want to support this as well. If anyone knows how to fix this, PRs welcome! 😄

**Comment by aMacDawg** [comment]
thanks @ashrafchowdury - I am pretty sure I tried the `double return/enter` keystroke before I wrote this issue, that does produce the expected outcome defined in the issue.

I am fine with closing the issue or leaving it open as a request for enhancement

**Comment by steven-tey** [comment]
@aMacDawg Let's leave it open as a request for enhancement! 😄 

Any Tiptap pros wanna tackle this – feel free to!
