### ISSUE TITLE
Selectors show on left top in Safari

### ISSUE THREAD

**Issue by ggukggukee** [steven-tey/novel#317]
### Provide environment information

System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 176.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm

### Describe the bug

<img width="572" alt="Screenshot 2024-02-29 at 12 58 27 PM" src="https://github.com/steven-tey/novel/assets/49220993/3934ece1-7958-4cbc-8f53-7c8b2cd714e2">

When selecting text bubble shows up on top of text

<img width="768" alt="Screenshot 2024-02-29 at 12 57 19 PM" src="https://github.com/steven-tey/novel/assets/49220993/67c2ca32-e42e-4e84-a42b-e8f1a907d2c2">

but when you click node, link or color selector it pops up on top left corner 

### Link to reproduction

https://novel.sh

### To reproduce

1. Select text
2. Click Link

**Comment by sahanatvessel** [comment]
+1

**Comment by sahanatvessel** [comment]
@shadcn @steven-tey keen to get your eyes on to this, I think this is a combination of radix/shadcn

**Comment by sahanatvessel** [comment]
related: https://github.com/radix-ui/primitives/issues/2779

**Comment by sahanatvessel** [comment]
@ggukggukee https://github.com/ueberdosis/tiptap/discussions/4145#discussioncomment-6907839 this worked for me

**Comment by JulianKominovic** [comment]
> @ggukggukee [ueberdosis/tiptap#4145 (comment)](https://github.com/ueberdosis/tiptap/discussions/4145#discussioncomment-6907839) this worked for me

Thanks @sahanatvessel.

In case this solution doesn't fit your needs you can stop using Portal. In my case Popover.Portal was the problem. Removing it solves the issue.
