### ISSUE TITLE
bug: Error with Ask AI features e.g Improve Writing, Fix Grammar in the latest main branch

### ISSUE THREAD

**Issue by thsonvt** [steven-tey/novel#332]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 16.71 GB / 31.91 GB
  Binaries:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

Hi there,

I cloned the latest version of main branch and tried 'Ask AI' feature. There is an error appear on the right hand side with all the AI features such as Improve Writing, Fix Grammar. 
Here is the screenshot of the error 
![image](https://github.com/steven-tey/novel/assets/843462/d0755b5c-1794-4ac2-a148-67110d844e8c)

Here is the recording of how the bug happened.

https://www.awesomescreenshot.com/video/25568430?key=5b8a9f70ffc486ae91d06006ab88cf1f

### Link to reproduction

https://www.awesomescreenshot.com/video/25568430?key=5b8a9f70ffc486ae91d06006ab88cf1f

### To reproduce

Hi there,

I cloned the latest version of main branch and tried 'Ask AI' feature. There is an error appear on the right hand side with all the AI features such as Improve Writing, Fix Grammar. 
Here is the screenshot of the error 
![image](https://github.com/steven-tey/novel/assets/843462/d0755b5c-1794-4ac2-a148-67110d844e8c)

Here is the recording of how the bug happened.

https://www.awesomescreenshot.com/video/25568430?key=5b8a9f70ffc486ae91d06006ab88cf1f

**Comment by parthgu** [comment]
Hey did this ever get fixed? Im getting the same issue.
