### ISSUE TITLE
bug: yarn novel can't find novel/extensions module

### ISSUE THREAD

**Issue by ZAJ0711** [steven-tey/novel#371]
### Provide environment information

react

### Describe the bug

when yarn add novel 
can't find novel/extensions module
import {
  TiptapImage,
  TiptapLink,
  UpdatedImage,
  TaskList,
  TaskItem,
  HorizontalRule,
  StarterKit,
  Placeholder,
} from "novel/extensions";
whitch can't import

### Link to reproduction

none

### To reproduce

none

**Comment by alexanderbnelson** [comment]
This has been mentioned before. I think you need to add `"moduleResolution": "bundler"` to you tsconfig.json `compilerOptions`

[#357](https://github.com/steven-tey/novel/issues/357#issuecomment-2016505161)
