### ISSUE TITLE
Cannot find module 'novel/extensions' or its corresponding type declarations.

### ISSUE THREAD

**Issue by reymondgomera** [steven-tey/novel#397]
i am using **novel: "^0.4.2",**

![error](https://github.com/steven-tey/novel/assets/85330066/172027dd-af2d-4ce1-a657-d749f61dbf06)

**Comment by andrewdoro** [comment]
Hey this library is no longer supporting `moduleResolution: "node"` in the tsconfig. Please check in your tsconfig if you are using a newer option. Novel demo is using "moduleResolution": "Bundler".

> you can also find a modern config here

https://www.totaltypescript.com/tsconfig-cheat-sheet

**Comment by reymondgomera** [comment]
i did change it to "moduleResolution": "Bundler" and it work. Thank you
