### ISSUE TITLE
bug: continue writing issue

### ISSUE THREAD

**Issue by mohe22** [steven-tey/novel#431]
### Provide environment information

 System:
    OS: Linux 6.6 Kali GNU/Linux Rolling 2024.2
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 7.10 GB / 15.41 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.20.1 - /usr/bin/node
    npm: 10.8.2 - /usr/local/bin/npm

### Describe the bug

when i use the /ai for continue writing by AI after getting the response it will show it after 1 second it will delete the text, but if i used ++ there is no issue. 

/api/generate

`import { HfInference } from "@huggingface/inference";

const inference = new HfInference(process.env.AI);

export const POST = async (request: Request): Promise<Response> => {
  const { prompt } = await request.json();

  const maxAllowedTokens = 8192; 
  const maxNewTokens = 500; 

  const autoComplete = ` 
    You are an AI writing assistant that continues existing text based on context from prior text.
    Give more weight/priority to the later characters than the beginning ones. 
    Limit your response to no more than 250 characters, but make sure to construct complete sentences.
    user:${prompt}
  `;

  const stream = new ReadableStream({
    async start(controller) {
      for await (const chunk of inference.chatCompletionStream({
        model: "meta-llama/Meta-Llama-3-8B-Instruct",
        messages: [
          {
            role: "user",
            content: autoComplete,
          },
        ],
        max_tokens: maxNewTokens,
      })) {
        const response = chunk.choices[0]?.delta?.content;
        if (response) {
          controller.enqueue(new TextEncoder().encode(response));
        }
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
`

video:

https://github.com/user-attachments/assets/b8c40083-93e3-4ba4-82d4-dfb4365578b2

### Link to reproduction

https://github.com

### To reproduce

.

### Additional information

https://github.com/user-attachments/assets/b8c40083-93e3-4ba4-82d4-dfb4365578b2

**Comment by bansi-hkapps** [comment]
i also given same issue please give me solution
and one more question novel latest version 0.5.0 why not working which node version support for latest version?
