### ISSUE TITLE
bug: editor.chain(...).focus(...).toggleUnderline is not a function when underlining a word

### ISSUE THREAD

**Issue by FreeSpirit777** [steven-tey/novel#435]
### Provide environment information

System:
    OS: Linux 6.1 Fedora Linux 38 (Thirty Eight)
    CPU: (3) x64 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
    Memory: 1.76 GB / 3.98 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 9.6.0 - /usr/local/bin/pnpm
    bun: 1.1.20 - ~/.bun/bin/bun

### Describe the bug

Hi, I'm working with the novel-tailwind-example. I have upgraded all packages to the newest versions but now I get the error: "TypeError: editor.chain(...).focus(...).toggleUnderline is not a function" when underlining a word and "TypeError: editor.commands.unsetColor is not a function" when trying to give another color. What can I do?

### Link to reproduction

https://github.com/steven-tey/novel/tree/main/examples/novel-tailwind

### To reproduce

See above

**Comment by jiaweing** [comment]
I have the same issue as well.

```
TypeError: editor.commands.unsetColor is not a function
```

**Comment by Darpan-favfly** [comment]
I have same issue please give us a solution

![image](https://github.com/user-attachments/assets/49f939b9-bccf-49b8-9fce-1ee721063f4b)
![image](https://github.com/user-attachments/assets/f78def2a-29b4-474a-907e-de540497a9de)

**Comment by Gaoridang** [comment]
What versions do you use? In my case, it works well.

```
{
  "name": "novel-tailwind",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@radix-ui/react-dropdown-menu": "^2.0.6",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@tailwindcss/typography": "^0.5.10",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "lucide-react": "^0.363.0",
    "next": "14.1.4",
    "next-themes": "^0.3.0",
    "novel": "^0.2.13",
    "react": "^18",
    "react-dom": "^18",
    "sonner": "^1.4.41",
    "tailwind-merge": "^2.2.2",
    "tailwindcss-animate": "^1.0.7"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
```

<img width="300" alt="스크린샷 2024-08-09 오후 11 42 39" src="https://github.com/user-attachments/assets/1ee438fd-a1ea-46bd-ad30-f9b8bb93dcf2">

**Comment by Gaoridang** [comment]
> I have same issue please give us a solution
> 
What versions do you use? In my case, it works well.

```
{
  "name": "novel-tailwind",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@radix-ui/react-dropdown-menu": "^2.0.6",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@tailwindcss/typography": "^0.5.10",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "lucide-react": "^0.363.0",
    "next": "14.1.4",
    "next-themes": "^0.3.0",
    "novel": "^0.2.13",
    "react": "^18",
    "react-dom": "^18",
    "sonner": "^1.4.41",
    "tailwind-merge": "^2.2.2",
    "tailwindcss-animate": "^1.0.7"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
```

<img width="300" alt="스크린샷 2024-08-09 오후 11 42 39" src="https://github.com/user-attachments/assets/1ee438fd-a1ea-46bd-ad30-f9b8bb93dcf2">

**Comment by mathiasrscom** [comment]
I got the same for for `editor?.chain().unsetHighlight().run()` I need to revert back until this is solved.

**Comment by Gaoridang** [comment]
I've made a PR for this issue. It may resolve the error!

**Comment by rajinsyed** [comment]
Getting the same issue. editor.chain(...).focus(...).setLatex is not a function

**Comment by yamz8** [comment]
> I've made a PR for this issue. It may resolve the error!

thanks for that, you don't have to wait for the pr, 

just add that to your extension file:

TiptapUnderline,
  Color,
  TextStyle,
  HighlightExtension.configure({
    multicolor: true,
  }),

**Comment by its-mohammadhosein** [comment]
I had same issue, I found out that if you're using custom extensions alongside the "StarterKit", Underline command wouldn't work, so you can install @tiptap/extension-underline by `npm i @tiptap/extension-underline` (or any other package manager you'd like), and add it to the `extensions` config in `useEditor({...})`, it worked for me

**Comment by tradex-app** [comment]
> you can install @tiptap/extension-underline by `npm i @tiptap/extension-underline` (or any other package manager you'd like), and add it to the `extensions` config in `useEditor({...})`, it worked for me

@its-mohammadhosein thank you! That's a fix for me. =)

**Comment by its-mohammadhosein** [comment]
@tradex-app here you are, and also I recommend you to check [this repo](https://github.com/AliBagheri2079/rich-text-editor) It literally solved my problems; (Fortunately/Unfortunately he has added Persian translated tooltip)
