### ISSUE TITLE
Weird indentation after deleting todo list item

### ISSUE THREAD

**Issue by uncenter** [steven-tey/novel#44]
If you have a task list and delete any task that isn't the first, you are stuck in a weird indentation state. Pressing <kbd>delete</kbd> returns you to the previous line, so the user has to to press <kbd>enter</kbd> (while on the line with the weird indentation) to remove the indentation. Pressing <kbd>enter</kbd> actually seems like the proper way to delete an empty item without the indentation.

https://github.com/steven-tey/novel/assets/47499684/a5f92c24-e4e8-42be-a0cf-e85b8abca3dc

There is also some other weird behavior with the indentation; if you have a line below the todo list (as I did to showcase the different indentation) while the strange indentation is happening, pressing delete while on that line below creates a new task. See 0:03 to 0:05 above.

**Comment by umeshjain1999** [comment]
Checkout this issue #31 state similar problem. Seems like this is how Tiptap has designed this behaviour to delete a line from bulletlist, tasklist, etc https://tiptap.dev/api/nodes/task-item#usage
