### ISSUE TITLE
Share your document?

### ISSUE THREAD

**Issue by patrickmast** [steven-tey/novel#45]
Can we have the ability to share the document with a public link?

PS. Was not able to set "Label" for this message to "enhancement"..

**Comment by steven-tey** [comment]
Yup, this is planned and is related to #11 :)

**Comment by jrc03c** [comment]
Also, you've probably got this covered somewhere, but I couldn't find it: Is there a way to download / export a document?

**Comment by cristigoia** [comment]
@jrc03c saw your comment after my post. Did a quick download as a markdown for myself here #148

**Comment by jrc03c** [comment]
@cristigoia Cool! Thanks for sharing!

**Comment by steven-tey** [comment]
Won't be adding this feature to Novel since it's more of a full-stack app feature – if you want, you can do `npm i novel` and implement your own database for persisting the contents instead! :)
