### ISSUE TITLE
Set Hyperlink on Text With Input UI

### ISSUE THREAD

**Issue by varun2948** [steven-tey/novel#46]
I wanted to contribute to this feature where a user can set a hyperlink on any text with some basic UI like this should I work on this ?
![image](https://github.com/steven-tey/novel/assets/37866666/7d0b2ce8-a5b3-4d2d-83ea-7db63c9f9d22)

**Comment by steven-tey** [comment]
Yes please! But let's make the UI much nicer – ideally it'll be similar to the Notion UI:

![CleanShot 2023-06-24 at 16 05 48](https://github.com/steven-tey/novel/assets/28986134/5f924d31-5345-44d2-abb6-ad1f35c2e6c0)
