### ISSUE TITLE
Support  Drag handles

### ISSUE THREAD

**Issue by Adonis0123** [steven-tey/novel#52]
Is it possible to implement drag handles similar to those in Notion?

![image](https://github.com/steven-tey/novel/assets/46788304/2dd4be5f-e38d-4640-be6a-fe08fb3b514b)

**Comment by mmailaender** [comment]
It seems that is something that is not yet fully solved in Tiptap itself: https://tiptap.dev/guide/node-views/examples#drag-handles

**Comment by Adonis0123** [comment]
> It seems that is something that is not yet fully solved in Tiptap itself: [tiptap.dev/guide/node-views/examples#drag-handles](https://tiptap.dev/guide/node-views/examples#drag-handles)

I have noticed that custom blocks like [blockNode ](https://www.blocknotejs.org/)or [notitap ](https://sereneinserenade.github.io/notitap/)are built on top of tiptap. they realized drag handles. I have been studying their code, but I find it challenging to understand how to customize a block. If anyone is interested in this topic, I would love to collaborate and learn together.

**Comment by steven-tey** [comment]
This is actually one of the top features planned for Novel! It's definitely doable, but needs a bit more thought. Planning to work on a PR soon 👀

**Comment by steven-tey** [comment]
Will be fixed by #122 <picture data-single-emoji=":yay:" title=":yay:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/yay/0f9ab09fef2702c1.gif" alt=":yay:" align="absmiddle"></picture>

**Comment by steven-tey** [comment]
This shipped! https://twitter.com/steventey/status/1699067429266334176
