### ISSUE TITLE
the "/" menu doesnt scroll when navigated with arrow keys

### ISSUE THREAD

**Issue by jailbreakerVC** [steven-tey/novel#6]
![image](https://github.com/steven-tey/novel/assets/54243183/c84da4b3-308f-4adc-ae6e-62fa999e326f)

**Comment by steven-tey** [comment]
Good catch! Didn't have time to fix this before launch – will look into it soon, but PRs welcome! :)

**Comment by steven-tey** [comment]
Kudos to the amazing Tiptap wizard @sereneinserenade for fixing this!
