### ISSUE TITLE
Collision detection for Selector dropdowns

### ISSUE THREAD

**Issue by steven-tey** [steven-tey/novel#64]
Currently, the Color and Node Selectors is unable to detect when it's near the bottom of the screen and has to be opened the other way round:

![CleanShot 2023-06-29 at 08 23 35](https://github.com/steven-tey/novel/assets/28986134/789b852e-630e-4f3c-9eeb-dac744ca1c5b)

Using something like a [Radix Popover](https://www.radix-ui.com/docs/primitives/components/popover) could fix this:

https://github.com/steven-tey/novel/assets/28986134/4f7551ff-6811-43a9-a819-485a41aec9ab

We'll also want to make sure to limit the height of the dropdown and add `overflow-scroll` depending on the screen height.

**Comment by abhijain1705** [comment]
is that repo is still active?

**Comment by steven-tey** [comment]
@abhijain1705 don't think a fixed height is the solution here, since you wouldn't know what position the bubble menu is initiated in the DOM and it might still collide with the screen boundaries 

> is that repo is still active?

Which repo are you referring to?

**Comment by abhijain1705** [comment]
then what can be best the solution here?
can we get current position of whole edit menu?

**Comment by abhijain1705** [comment]
it's like redeveloping the menu using Radix popover 
correct me if I am wrong

**Comment by steven-tey** [comment]
Exactly!

**Comment by abhijain1705** [comment]
can I contribute to this?

**Comment by abhijain1705** [comment]
hey @steven-tey  you might busy previously
can I contribute to this?

**Comment by steven-tey** [comment]
@abhijain1705 yes, of course! :)

**Comment by abhijain1705** [comment]
thanks
