### ISSUE TITLE
Adding width to document for wider text documents

### ISSUE THREAD

**Issue by walter-grace** [steven-tey/novel#66]
What is the easiest way to add width to the document, I am trying to create it for screenwriters or playwrights and the format gets crunched. Is there any easier way to change the formatting component?

**Comment by steven-tey** [comment]
Just pushed a commit that should fix this: https://github.com/steven-tey/novel/commit/d5a3b29484e445cc01a03c8190b02ef2fc359ff3

Can you check and confirm if that's the case?

**Comment by walter-grace** [comment]
Added a comment to the commit : for me it still is giving the format issue. I am copying it over from a screenplay document.
