### ISSUE TITLE
flushSync issue when adding an Image from Slash Command

### ISSUE THREAD

**Issue by upview** [steven-tey/novel#69]
Hi there, and thank you for your excellent implementation. Trying to replicate it locally I got everything working, except the "Image" option from the slash command menu. I keep getting 

`Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.` 

that seems to be caused by the `view.dispatch(transaction)`. Usually its triggered when I insert 2 images in a row, the 1st image is fine. It's working fine from onDrop or onPaste events, but not with the event when slash option is selected. 

I am unsure what I could do to solve this issue, do you have any clue? Thanks a lot :)

**Comment by steven-tey** [comment]
Oh good question, haven't dealt with multiple images before – PRs welcome! 👀

**Comment by upview** [comment]
Understood the issue and found a fix here https://github.com/ueberdosis/tiptap/pull/4000. Not an issue of Novel, multiple image upload works well.
