### ISSUE TITLE
Can we have a Monospaced font?

### ISSUE THREAD

**Issue by patrickmast** [steven-tey/novel#77]
In the font menu, can we have a Monospaced font. So I can share programming code?
Thanks!

**Comment by steven-tey** [comment]
You can already do that with a code-block feature!

![CleanShot 2023-07-06 at 16 13 42](https://github.com/steven-tey/novel/assets/28986134/1b47955c-6e43-4c5b-952d-7e8399322027)

Planning to add more fonts + support for syntax highlighting soon though!

**Comment by steven-tey** [comment]
Added a monospace font in the switcher!

![Uploading CleanShot 2023-07-07 at 17.04.09.png…]()

**Comment by mariusbolik** [comment]
+1 for syntax highlighting! `highlight.js` seems like a good solution :)
