### ISSUE TITLE
shash commands can appear anywhere?

### ISSUE THREAD

**Issue by tsl1127** [steven-tey/novel#82]
**now**: It allows you to start a new line with / and will bring up a popup to select which node should be added
**hope**: type / anywhere will bring up a popup

**Comment by steven-tey** [comment]
It does appear anywhere:

![CleanShot 2023-07-08 at 11 07 30](https://github.com/steven-tey/novel/assets/28986134/5460785f-7be7-4cd5-8c26-598e525ceb18)

**Comment by tsl1127** [comment]
If there is a space in front of /, it does appear; but if there is no space in front of / or other letters are connected, it does not
![image](https://github.com/steven-tey/novel/assets/32303633/08c41035-9eac-416c-ba86-8016dafdd01d)
@steven-tey
