### ISSUE TITLE
When I deploy to Vercel and use autocomplete I get "Something went wrong" error

### ISSUE THREAD

**Issue by neuroradiology** [steven-tey/novel#9]
When I deploy to Vercel and use autocomplete by using either ++ or the slash menu I get a message "Something went wrong" in a pop-up in the lower right corner.

The error log shows status 429 ("too many requests") coming back from OpenAI, but this is unexpected because I haven't used it for anything else, and it happened with my first request. 

This may be a problem on the OpenAI side.

**Comment by steven-tey** [comment]
That's weird – maybe try removing [this part of the code](https://github.com/steven-tey/novel/blob/main/app/api/generate/route.ts#L14-L39)?

But it shouldn't happen if you didn't specify the Vercel KV env vars though!

**Comment by linas23** [comment]
I removed the part of the code you mentioned. But it still prompts that "Something went wrong" message.

**Comment by steven-tey** [comment]
Maybe the API key you're using is running into OpenAI limits?

**Comment by GraemeFulton** [comment]
Adding API key fixed this for me - I had the same error and forgot to add my own .env

**Comment by steven-tey** [comment]
@dewanshchaudhari added an `.env.example` file so we should be good here: #20

Closing for now!
