### ISSUE TITLE
Image resizing feature

### ISSUE THREAD

**Issue by ashrafchowdury** [steven-tey/novel#92]
## Description

The current editor does not have an image resizing feature. This means that users are unable to resize images to fit their desired size. This can be a problem for users who want to use images in their content but don't need the full size of the image. 

## Solution
The proposed solution is to add an image resizing feature to the editor. This feature would allow users to resize images to a specific width, or height of the original size. The feature would also allow users to maintain the aspect ratio of the image when resizing.

## Feature Example

https://github.com/steven-tey/novel/assets/87828904/912b1fa6-030c-4071-83a5-07e06f36eaac

**Comment by Ansub** [comment]
@steven-tey this issue can be closed now :)
