### ISSUE TITLE
Disable or remove EditorBubbleMenu on read only mode

### ISSUE THREAD

**Issue by ghikurniawan** [steven-tey/novel#96]
### The "EditorBubbleMenu" remains active when the editor is in readonly mode.

I want to make my blog editable in real-time, based on the session and author. However, I have an issue with the novel editor, where the "EditorBubbleMenu" **still runs** when the editor is in readonly mode.

## #Demo
[Demo](https://iwwwan.vercel.app/editor)

Go to File > publish to make editor read only mode

I'm using this code to make the editor disabled or readonly mode.

```
const [canEdit, setCanEdit] = useState(true);
...
useEffect(() => {
    editor?.setEditable(canEdit); // toggle editable
 }, [editor, canEdit]);

...

```

[Tab-1689375707183.webm](https://github.com/steven-tey/novel/assets/91013444/20d639db-9619-4ad1-af43-9043c10ba58e)

**Comment by steven-tey** [comment]
Closing this for now since we don't have readonly mode yet (and probably would want to put more thought into that when we build it)!

Thanks a lot though!

**Comment by cloudnothings** [comment]
Any plan on creating a read-only mode at this point?

Thank you!

**Comment by AKRking** [comment]
thats very strange that a editor doesnt have a readonly mode.very very strange.
